// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace EmpleoDotNet.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JobOpportunityIsRemoteField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobOpportunityIsRemoteField));
        
        string IMigrationMetadata.Id
        {
            get { return "201601142153385_JobOpportunityIsRemoteField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
