// <auto-generated />
namespace EmpleoDotNet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_UserProfile_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_UserProfile_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201602260327441_Add_UserProfile_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
